# Where should we write the GIF?
Output sealed-secrets-buffer.gif

Set FontSize 23
Set Margin 5
Set MarginFill "#8b9bf7"
Set BorderRadius 10
Set Width 2300
Set Height 1200
Set Theme "TokyoNightStorm"
Set Shell zsh

Hide
Type "source /home/tinoschroeter/.zshrc "
Enter
Sleep 2s
Type clear
Enter
Show
Type@300ms "vim secrets.yaml"
Enter
Sleep 4s
Space
Sleep 3s
Type "k"
Sleep 3s
Type "s"
Sleep 8s
Type "ZZ"
